//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CatCLSLib.rc
//
#define IDS_PROJNAME                    100
#define IDR_CATCLSLIB                   101
#define IDS_BUY_NOW                     101
#define IDR_CORE                        102
#define IDS_CODECENTRIX_BUY_TWEBST_URL  102
#define IDR_BROWSER                     103
#define IDS_VERSION_STATIC_TEXT         103
#define IDR_FRAME                       104
#define IDR_ELEMENT                     105
#define IDR_BROWSERLIST                 106
#define IDR_FRAMELIST                   107
#define IDR_ELEMENTLIST                 108
#define IDI_TWBST_ICON                  203
#define IDC_CONTINUE_BUTTON2            205
#define IDC_CONTINUE_BUTTON3            207
#define IDS_ERR_CAN_NOT_START_BROWSER   512
#define IDS_ERR_CAN_NOT_START_BROWSER_BECAUSE_OF_PROXY 513
#define IDS_WAIT_TO_LOAD_TIMEOUT        529
#define IDS_FIND_ALL_BRWS_LOAD_TIMEOUT  532
#define IDS_ERR_INDEX_OUT_OF_BOUNDS     536
#define IDS_ERR_FIND_ELEMENT_INVALID_PARAM 539
#define IDS_ERR_FIND_ELEMENT_FAILED     540
#define IDS_ERR_BROWSER_DISCONNECTED    541
#define IDS_FIND_ELEMENT_LOAD_TIMEOUT   542
#define IDS_ERR_CAN_NOT_CREATE_ELEMENT  543
#define IDS_ERR_CAN_NOT_CREATE_FRAME    546
#define IDS_ERR_FIND_CHILD_ELEMENT_INVALID_PARAM 548
#define IDS_ERR_FIND_CHILD_ELEMENT_FAILED 549
#define IDS_FIND_CHILD_ELEMENT_LOAD_TIMEOUT 550
#define IDS_ERR_FIND_FRAME_INVALID_PARAM 551
#define IDS_ERR_FIND_FRAME_FAILED       552
#define IDS_FIND_FRAME_LOAD_TIMEOUT     553
#define IDS_ERR_FIND_CHILD_FRAME_INVALID_PARAM 554
#define IDS_FIND_CHILD_FRAME_LOAD_TIMEOUT 555
#define IDS_ERR_FIND_CHILD_FRAME_FAILED 556
#define IDS_ERR_FIND_ALL_ELEMENTS_INVALID_PARAM 562
#define IDS_ERR_FIND_ALL_ELEMENTS_FAILED 563
#define IDS_ERR_CAN_NOT_CREATE_ELEMENT_LIST 564
#define IDS_FIND_ALL_ELEMENTS_LOAD_TIMEOUT 565
#define IDS_ERR_FIND_CHILDREN_ELEMENTS_FAILED 566
#define IDS_ERR_FIND_CHILDREN_ELEMENTS_INVALID_PARAM 567
#define IDS_FIND_CHILDREN_ELEMENTS_LOAD_TIMEOUT 568
#define IDS_ERR_FIND_FRAMES_INVALID_PARAM 569
#define IDS_ERR_FIND_FRAMES_FAILED      570
#define IDS_FIND_FRAMES_LOAD_TIMEOUT    571
#define IDS_ERR_CAN_NOT_CREATE_FRAME_LIST 572
#define IDS_ERR_FIND_ALL_FRAMES_INVALID_PARAM 573
#define IDS_ERR_FIND_ALL_FRAMES_FAILED  574
#define IDS_FIND_ALL_FRAMES_LOAD_TIMEOUT 575
#define IDS_ERR_FIND_CHILDREN_FRAMES_INVALID_PARAM 576
#define IDS_ERR_FIND_CHILDREN_FRAMES_FAILED 577
#define IDS_FIND_CHILDREN_FRAMES_LOAD_TIMEOUT 578
#define IDS_ERR_INVALID_OPERATION       586
#define IDS_ERR_CAN_NOT_CREATE_BROWSER  588
#define IDS_INVALID_PARAM_LIST_IN_METHOD 590
#define IDS_METHOD_CALL_FAILED          591
#define IDS_PROPERTY_FAILED             592
#define IDS_OPTION_ELEMENT_NOT_FOUND    593
#define IDS_ERR_CANCELED                594
#define IDS_ERR_FIND_HTML_DIALOG_INVALID_PARAM 596
#define IDS_ERR_FIND_HTML_DIALOG_FAILED 597
#define IDS_FIND_HTML_DIALOG_LOAD_TIMEOUT 598
#define IDS_ERR_FIND_MODAL_HTML_DIALOG_INVALID_PARAM 599
#define IDS_ERR_FIND_MODAL_HTML_DIALOG_FAILED 600
#define IDS_FIND_MODAL_HTML_DIALOG_LOAD_TIMEOUT 601
#define IDS_ERR_FIND_PARENT_ELEMENT_INVALID_PARAM 602
#define IDS_ERR_FIND_PARENT_ELEMENT_FAILED 603
#define IDS_FIND_PARENT_ELEMENT_LOAD_TIMEOUT 604
#define IDS_INVALID_FILE_PATH_IN_INPUT_TEXT 605
#define IDS_TAB_NOT_ACTIVE              606
#define IDS_INPUT_TEXT_TAB_NOT_ACTIVE   606
#define IDS_ERR_SELECTED_OPTION_INVALID_PARAM 607
#define IDS_ERR_SELECTED_OPTION_FAILED  608
#define IDS_SELECTED_OPTION_LOAD_TIMEOUT 609
#define IDS_SELECT_OPTIONS_LOAD_TIMEOUT 610
#define IDS_ERR_GET_ALL_SEL_OPTIONS_INVALID_PARAM 611
#define IDS_ERR_GET_ALL_SEL_OPTIONS_FAILED 612
#define IDS_GET_ALL_SEL_OPTIONS_LOAD_TIMEOUT 613
#define IDS_BROWSER_CLOSE_POPUP_TIMEOUT 614
#define IDS_CLOSE_POPUP_BUTTON_NOT_FOUND 615
#define IDS_CLOSE_POPUP_EDIT_NOT_FOUND  616
#define IDS_UPGRADE_NOW                 617
#define IDS_CODECENTRIX_UPGRADE_TWEBST_URL 618

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         205
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
