#pragma once

namespace XBit
{
	const TCHAR XBIT_INJECTOR_WND_NAME[]           = _T("{DF03E991-B570-42EB-952A-4D231171D774}");
	const TCHAR XBIT_INJECTOR_WND_CLASS_NAME_x86[] = _T("{AD3D7031-DCE3-4ec8-B621-86ADFA490C20}_x86");
	const TCHAR XBIT_INJECTOR_WND_CLASS_NAME_x64[] = _T("{AD3D7031-DCE3-4ec8-B621-86ADFA490C20}_x64");
	const WCHAR XBIT_START_IE_CMDL[]               = L"/S";
	const TCHAR XBIT_INJECTOR_EXE_NAME_X86[]       = _T("TwbstXbit_x86.exe");
	const TCHAR XBIT_INJECTOR_EXE_NAME_X64[]       = _T("TwbstXbit_x64.exe");

#ifdef _AMD64_
	const LPCTSTR XBIT_INJECTOR_EXE_NAME       = XBIT_INJECTOR_EXE_NAME_X86;
	const LPCTSTR XBIT_INJECTOR_WND_CLASS_NAME = XBIT_INJECTOR_WND_CLASS_NAME_x86;
#else
	const LPCTSTR XBIT_INJECTOR_EXE_NAME        = XBIT_INJECTOR_EXE_NAME_X64;
	const LPCTSTR XBIT_INJECTOR_WND_CLASS_NAME = XBIT_INJECTOR_WND_CLASS_NAME_x64;
#endif

	const UINT  XBIT_MSG_INJECT_BHO = WM_APP + 1;
}
